### PR TITLE
fix: Restart notifier failing TXs until success

### LINKED ISSUE #1198: retry failed transactions from the sui executor
use retry with max elapsed time with 10 minutes within an infinite loop

### PR DESCRIPTION
**Pull request by ItayLevyOfficial**
Until now we ignored errors that have been emitted within the move code, and we didn't re-submit transactions that failed due to such errors. This PR mitigates this issue by checking for such errors, and retry submitting those TXs with a 24 hours exponential backoff.

### CODE REVIEW

File: crates/ika/src/ika_commands.rs [hunk 1]
```diff
@@ -22,7 +22,7 @@ use sui_sdk::wallet_context::WalletContext;
 use tokio::runtime::Runtime;
 use tracing::info;
 
-const DEFAULT_EPOCH_DURATION_MS: u64 = 1000 * 60 * 60 * 24;
```
Comment (zeevmoney) [inline crates/ika/src/ika_commands.rs]: revert

Comment (zeevmoney) [reply crates/ika/src/ika_commands.rs]: and use flags, don't change it each time.

File: crates/ika-sui-client/src/lib.rs [hunk 2]
```diff
@@ -77,10 +77,10 @@ macro_rules! retry_with_max_elapsed_time {
                     Ok(_) => {
                         return Ok(result);
                     }
-                    Err(e) => {
+                    Err(err) => {
                         // For simplicity we treat every error as transient so we can retry until max_elapsed_time
-                        debug!("Retrying due to error: {:?}", e);
-                        return Err(backoff::Error::transient(e));
+                        error!(?err, "Retrying due to error");
```
Comment (zeevmoney) [inline crates/ika-sui-client/src/lib.rs]: this err message is very ambiguous, make it clearer.

File: crates/ika-core/src/sui_connector/sui_executor.rs [hunk 3]
```diff
@@ -1106,7 +1112,17 @@ where
         )
         .await;
 
-        Ok(Self::submit_tx_to_sui(notifier_tx_lock, transaction, sui_client).await?)
+        let result = Self::submit_tx_to_sui(notifier_tx_lock, transaction, sui_client).await;
+        if result.is_err() {
+            metrics.system_checkpoint_writes_failure_total.inc();
+            let err = result.err();
+            error!(
+                "failed to submit system checkpoint to consensus, error: {:?}",
```
Comment (zeevmoney) [inline crates/ika-core/src/sui_connector/sui_executor.rs]: use error=...

File: crates/ika-core/src/sui_connector/sui_executor.rs [hunk 4]
```diff
@@ -1106,7 +1112,17 @@ where
...
+                &err
+            );
+            return Err(err.unwrap().into());
```
Comment (zeevmoney) [inline crates/ika-core/src/sui_connector/sui_executor.rs]: why unwrap?

File: crates/ika-core/src/sui_connector/sui_executor.rs [hunk 5]
```diff
@@ -1106,7 +1112,17 @@ where
         )
         .await;
 
-        Ok(Self::submit_tx_to_sui(notifier_tx_lock, transaction, sui_client).await?)
+        let result = Self::submit_tx_to_sui(notifier_tx_lock, transaction, sui_client).await;
+        if result.is_err() {
```
Comment (zeevmoney) [inline crates/ika-core/src/sui_connector/sui_executor.rs]: use match or some other way

**Review by zeevmoney — CHANGES_REQUESTED** [review]
Fix errors, remove unused imports, fix clippy, and why 24 hours?

File: crates/ika-core/src/sui_connector/sui_executor.rs (hunk 4 above)
Comment (ItayLevyOfficial) [reply crates/ika-core/src/sui_connector/sui_executor.rs]: I'm checking five lines before
```
if result.is_err() {
```

File: crates/ika-core/src/sui_connector/sui_executor.rs [hunk 6]
```diff
@@ -1017,7 +1019,11 @@ where
...
+            metrics.dwallet_checkpoint_writes_failure_total.inc();
```
Comment (zeevmoney) [inline crates/ika-core/src/sui_connector/sui_executor.rs]: add error log same as system

**Review by zeevmoney — APPROVED** [review]
